### ISSUE TITLE
Hover  effects and colors are too subtle

### ISSUE THREAD

**Issue by salmanulfarzy** [meain/pbbui#1]
Awesome job with the website :clap: 

One minor suggestion, Contrast between the card and background are very subtle and shadow on card hovers makes it a bit difficult to identify which card is currently focused.

**Comment by meain** [comment]
![scr](https://i.imgur.com/C4PUkPh.png)

Does this look good?

**Comment by salmanulfarzy** [comment]
If you're okay with bit more vibrant color combination, I could suggest few. Also how about adding a small displacement using transform on hover ?

**Comment by meain** [comment]
I personally am not a big fan of a lot of vibrant colors, but I am open to suggestions.
